version: '3'

services:
  zookeeper:
    container_name: myZookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - exam-net

  kafka:
    container_name: myKafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - exam-net

  cdc:
    container_name: cdc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    command: sh -c "
      echo 'waiting 10s' &&
      sleep 10 &&
      /etc/confluent/docker/run"
    environment:
      CONNECT_GROUP_ID: 'cdc-outbox'
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_CONFIG_STORAGE_TOPIC: 'cdc-outbox-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'cdc-outbox-offset'
      CONNECT_STATUS_STORAGE_TOPIC: 'cdc-outbox-status'
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: cdc-outbox
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
    depends_on:
      - exam-db
      - zookeeper
      - kafka
    networks:
      - exam-net

  exam-db:
    container_name: exam-db
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./init-sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks:
      - exam-net

  order-service:
    container_name: order-service
    image: order-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - exam-db
    networks:
      - exam-net

  shipment-service:
    container_name: shipment-service
    image: shipment-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
      - exam-db
    networks:
      - exam-net

networks:
  exam-net: